### ISSUE TITLE
open-menu-with-item dissable broken

### ISSUE THREAD

**Issue by zax71** [MediusEcho/ParticleHats#10]
When the setting `menu.open-menu-with-item.enabled` to false in `config.yml` the item will show an error that it cannot find the menu `particles.yml` on right click.

Chat message: [https://sxcu.net/5rUxSgwZS](https://sxcu.net/5rUxSgwZS) (image)

Config: [https://paste.gg/p/Zax71/b19185639db74022800a44e0ebe3f84f](https://paste.gg/p/Zax71/b19185639db74022800a44e0ebe3f84f)

Temporary solution for anyone with the same issue: set `menu.open-menu-with-item.id` to `AIR`

**Comment by MediusEcho** [comment]
Looks like I forgot to check the value of `menu.open-menu-with-item.enabled`. I'll submit an update shortly with a fix.

**Comment by zax71** [comment]
Thanks for the quick reply! I’ll look forward to the update :)

**Comment by MediusEcho** [comment]
This issue has been fixed in the [4.2.15](https://www.spigotmc.org/resources/particlehats.1007/update?update=450793) update. Thanks for letting me know.
