### ISSUE TITLE
How to set permissions?

### ISSUE THREAD

**Issue by 9dolanla** [MediusEcho/ParticleHats#11]
Give particlehats.command.h the player can use all effects
How to make each effect have a permission?

**Comment by MediusEcho** [comment]
Each particle in the default menu is using the `override` action which will ignore permissions. You will need to edit each particle effect in the menu and set their action to `equip`. This can be done through the menus .yml file or you can use `/h edit particles` to open the in-game editor. Each particle effect is given the permission `particlehats.particle.all` by default, you can change this permission for each particle effect in the menu if you want to give players access to certain particle effects.
