### ISSUE TITLE
API Equip message

### ISSUE THREAD

**Issue by bigdaddyky** [MediusEcho/ParticleHats#13]
ParticleHats Version: 4.2.16
Minecraft Version: 1.19.2

Using the method: equipHatFromLabel() has a parameter to whether or not the player in question should receive a message stating the hat was equipped; however, is impractical because either or still results in there being a message being sent to the direct player.

Here are some screenshots:
`        try {
            hatsAPI.equipHatFromLabel(player, label, true);
        } catch (InvalidLabelException e) {
            e.printStackTrace();
        }`

![image](https://user-images.githubusercontent.com/80833366/216230295-479f06e0-b1a3-4660-b8c9-0c9d17b0b473.png)

`        try {
            hatsAPI.equipHatFromLabel(player, label, false);
        } catch (InvalidLabelException e) {
            e.printStackTrace();
        }`

![image](https://user-images.githubusercontent.com/80833366/216230386-a5ab39f2-1bbd-4405-924d-0eb42f428b11.png)

As you can see from above, you receive "<hat name> equipped" making the method above redundant and impractical.

I'm not sure if anybody else has experienced this issue; however, a temporary solution would just to use the 'h set' command and executing it through your code instead.

Unrelated:

I would like to suggest configuration values for the 'h set' command's demo feature & a menu demo set feature (Could be the same value for both stored in config.yml). Thumbs up to entire development on this plugin, been using it for a hot while now and haven't ran into anything damaging. Huge props.

**Comment by MediusEcho** [comment]
Just took a look at the code and yeah, I forgot to disable the equip message from the API. Thanks for letting me know.

> I would like to suggest configuration values for the 'h set' command's demo feature & a menu demo set feature (Could be the same value for both stored in config.yml).
Could you provide an example for what you're suggesting? I'm not sure I follow.

**Comment by MediusEcho** [comment]
Fixed in v4.2.18
