### ISSUE TITLE
Particle Offset as a static particle does not apply the same to the animation.

### ISSUE THREAD

**Issue by bigdaddyky** [MediusEcho/ParticleHats#15]
Hello. The title sums up my issue but i'm trying to make particles that kinda sit on the back of a player; however, I have noticed that the particle offset kinda resets it's position and does not budge when turned into the animated version of itself.

I tried this with the 'hoop' particle type.

How it's suppose to work:
![image](https://user-images.githubusercontent.com/80833366/233795036-9e4c777c-786d-4240-babc-298edb8fd63f.png)
![image](https://user-images.githubusercontent.com/80833366/233795059-d8103197-b975-4a73-815c-4ba9e3b2ef6c.png)

Turning it into the animation version:
![image](https://user-images.githubusercontent.com/80833366/233795093-539f808f-78c1-4b81-a493-6f71000873da.png)

I encountered this trying to create a galaxy'esk particle that sits on the back of the player.

**Comment by MediusEcho** [comment]
Would you be able to provide the other properties you've editing in your example? I found a fix and would like to recreate your effect to make sure.

**Comment by bigdaddyky** [comment]
![image](https://user-images.githubusercontent.com/80833366/234090571-28a22155-9654-475d-9b12-619c4f003405.png)
![image](https://user-images.githubusercontent.com/80833366/234090598-7bdd450d-0c73-41e7-b82c-be462c3efe18.png)
![image](https://user-images.githubusercontent.com/80833366/234090674-db0a61a7-1d3c-4334-9da7-9cae11fde7f3.png)
![image](https://user-images.githubusercontent.com/80833366/234090698-8eb772b4-f593-4857-9b42-6257a1a59262.png)
![image](https://user-images.githubusercontent.com/80833366/234090716-08242018-ce38-490e-84ac-2d35c750df7b.png)

This should be all. if i'm missing anything, let me know!

**Comment by MediusEcho** [comment]
Thanks, I've submitted an update that should fix the issue.
