### ISSUE TITLE
Effect still there when I disable the particle

### ISSUE THREAD

**Issue by FortStomper** [MediusEcho/ParticleHats#2]
I changed it in the config so that you can only wear one particle at a time. So if one is equipped and the person equips a new one, the old particle deactivates automatically (since only 1 particle can be worn). But if the previous particle had a potion effect (for example speed), then it still was there. So the new particle is activated and the old deactivated but the effect is still there. I'm not sure if anyone had this issue to but I'd be glad if that would be fixed. (no bungee, spigot 1.8.8 and newest plugin version). Thanks in advance and for reading this issue.

**Comment by MediusEcho** [comment]
The issue has been fixed in the 4.2.4 update. Thanks for letting me know.
