### ISSUE TITLE
Custom Particle Types rendering with pink or black background

### ISSUE THREAD

**Issue by NagisaStreams** [MediusEcho/ParticleHats#20]
I looked into the types of extra effects that the plugin comes with as a base, and I can tell they all use a pink background. If I use the pink background for my image, it puts it in-game. if I do not put a background, I get a black background. If I am missing something please let me know, I just want to make a logo float above the player. 

This is on version v 4.5.0 on 1.20.4

Initial Image (Downscaled)
![ZPLOGO](https://github.com/MediusEcho/ParticleHats/assets/23243364/be024fc7-37ee-4c47-9689-f7e7c7eae9ee)

Attempted Edit
![zppixel3](https://github.com/MediusEcho/ParticleHats/assets/23243364/be061402-6301-4516-ab22-6c564ef289d9)

Ends up looking like this.
![2024-06-10_16 40 22](https://github.com/MediusEcho/ParticleHats/assets/23243364/e1341073-df80-49ea-b3cb-8c2d6e1e186d)

Version without the pink:
![2024-06-10_16 41 16](https://github.com/MediusEcho/ParticleHats/assets/23243364/90bb063d-8c98-418d-af2f-4b9b46ec05a7)

**Comment by MediusEcho** [comment]
It looks like there might be some variations in the pink color. I recreated the image using pink (255, 0, 255) and it works. 

![before_after](https://github.com/MediusEcho/ParticleHats/assets/8467849/2dde4bf9-5c32-45ce-928e-683da0330182)

**Comment by NagisaStreams** [comment]
I went and tried editing it again to 255, 0, 255 and got 

![2024-06-10_20 53 37_2](https://github.com/MediusEcho/ParticleHats/assets/23243364/cb47b80c-38e6-42c4-ba99-666f03072c60)

from
![zptest4](https://github.com/MediusEcho/ParticleHats/assets/23243364/cdc2a9f2-4c30-4b65-ace3-d6ef33466429)

Here is the image in an editor showing it is 255, 0, 255 (bottom right)
![image](https://github.com/MediusEcho/ParticleHats/assets/23243364/eda0356a-c13f-4c30-9578-d2a62f4fcf17)

**Comment by MediusEcho** [comment]
Inspecting some of the pixels in Gimp shows that the background color is not all uniform, there are pixels that range from (254, 0, 255) to (255, 0, 254). I used Gimp's Select by Color tool with a 0 threshold to outline the pixels that don't match. 

![gimp_select_by_color](https://github.com/MediusEcho/ParticleHats/assets/8467849/7278e2cc-160c-4725-acbd-17e25b13c732)

**Comment by NagisaStreams** [comment]
Guess the editor I'm using is just bad.  Thank you I will try again when I get home.

**Comment by NagisaStreams** [comment]
I eventually got it to work by using Gimp and manually checking each pixel. Thank you for all the help!
