### ISSUE TITLE
Particle Hats creates bugs in MMOItems

### ISSUE THREAD

**Issue by slvlr** [MediusEcho/ParticleHats#5]
https://git.lumine.io/mythiccraft/mmoitems/-/issues/338

Please see above URL, MMOItems have said that ParticleHats needs to update the code, as it shouldn't be un-cancelling the pickup event when the ability "present drop" is thrown into hoppers.
Please advise?

**Comment by MediusEcho** [comment]
Oh wow, I'm suprised that hasn't caused issues until now. I'll get an update out asap to fix it.

**Comment by MediusEcho** [comment]
Update is out. Thanks for letting me know.
