### ISSUE TITLE
Feature Request: Limiting specific particles per world

### ISSUE THREAD

**Issue by IsXGeo** [MediusEcho/ParticleHats#6]
I'd like to have certain particles (or particle pages) enabled on specific worlds. For instance I'd like for my pvp server to have most particles enabled in the lobby world but then only particles used with a bow which are in a seperate yml file to be usable in the pvp worlds as well as the lobby.

**Comment by MediusEcho** [comment]
I'd like to add this feature at some point. I like the idea of enabling menus in certain worlds. This would allow Permissions & Economy plugins to still work as intended.
