### ISSUE TITLE
Async Request?

### ISSUE THREAD

**Issue by skw359** [MediusEcho/ParticleHats#7]
So this isn't really an issue, but probably could be on bigger servers. Basically, is there a way where ParticleHats can be run asynchronously? On small servers, it's not a big deal but for larger servers, it'll probably bog it down, as noted by some people. Just a feature request to make the plugin better as it already is, thanks! :)

**Comment by MediusEcho** [comment]
I agree. Definitely something I want to add sooner rather than later.

**Comment by MediusEcho** [comment]
Asynchronous particles have been added in the [4.2.11](https://www.spigotmc.org/resources/particlehats.1007/update?update=407277) update
