### ISSUE TITLE
visual bug

### ISSUE THREAD

**Issue by iQworte** [MediusEcho/ParticleHats#9]
When user Removing particle from ''Equipped Particles'' menu, it goes to the main menu to select effects. 
But at the same time, he still has the appearance that the effect he has already removed is still equipped.
https://disk.yandex.ru/i/PihOzhb_LWHqpA

And I have a problem with displaying some effects, I just don't see them.
-Creeper Face
-Angel Wings
-Rocket Tail
-Bubble WIngs
-Walking Billboard

**Comment by MediusEcho** [comment]
Can confirm the visual equipped bug. Thanks for letting me know.

The Rocket Trail particle effect only works when gliding with an Elytra, that effect works fine from my testing. 
I'll see what is causing those other particle effects to not work.

**Comment by MediusEcho** [comment]
I have pushed an update [[4.2.14]](https://www.spigotmc.org/resources/particlehats.1007/update?update=434929) that fixes the issues.

**Comment by iQworte** [comment]
Cool! Thank you)
